### ISSUE TITLE
Some G'mic Simulate Film filters are not working

### ISSUE THREAD

**Issue by gorremu** [GreycLab/gmic#389]
I have Ubuntu 20.04 - G'MIC-Qt for GIMP 2.10 - Linux 64 bits - 2.9.6

There are some filters (particularly most of the Black & White filters) on the Simulate Film that are simply not working. I get an error message stating "*** Error in ./fx_simulate_film/*if/clut/(...)/*if/*repeat/*local/*if/ *** Command 'input': Unrecognized function call 'repeat( h#0,k, for (l = 0, l<=k, ++l, r = norm(X[k] - X[l],(...)' in expression '...repeat( h#0,k, for (l = 0, l<=k, ++l, r = norm(X[k] - X[l],(...)...'."

Can anybody help me sorting this out?

**Comment by dtschump** [comment]
`repeat()` is a function that does not exist in G'MIC 2.9.6.
So I see two causes here:
- Maybe we have pushed a filter update file for 2.9.6 that is incorrect (contains calls to `repeat()` while it shouldn't be allowed in 2.9.6).
- Or maybe you got a wrong update file by any means (manual update ?).

The solution is to update your G'MIC plug-in to latest version (3.1.2 currently, soon 3.1.3), where this issue does not happen.

**Comment by dtschump** [comment]
I have Ubuntu 20.04 as well, and I'm installing G'MIC from the provided .deb package.
Open your command line and type:
~~~
wget https://gmic.eu/files/prerelease/gmic_ubuntu20-04_focal_amd64.deb && sudo dpkg -i gmic_ubuntu20-04_focal_amd64.deb
~~~
You'll get the latest `development` version of G'MIC, which is the most up-to-date.

**Comment by gorremu** [comment]
I typed what you asked but when I try using it through GIMP it's still showing version 2.9.6 and I'm getting the same error message.

I'm using GIMP 2.10.28 (it's not the latest version). Could this be an issue?

On a side note: I just realized I'm actually talking to the author of the software! Thank you for this. I love using G'MIC! It's very nice to meet you Mr. Tschumperlé.

**Comment by dtschump** [comment]
> I typed what you asked but when I try using it through GIMP it's still showing version 2.9.6 and I'm getting the same error message.

This probably means that your older version of the plug-in is installed locally, and takes precedence over the one installed by the `.deb` package.
You may check:
- That the local plug-in directory `$HOME/.config/GIMP/2.10/plug-ins/` does not contain an older `gmic_gimp_qt` binary. If so, delete it.
- That when you type `gmic -version` on the command line, you see version `3.1.3` (pre-release). This means the `.deb` package has been installed correctly.
- Then, if you still get the 2.9.6 version of the plug-in when you launch GIMP, you have to find in what folder the older binary of the plug-in stays. For this, you can check, in GIMP, `Edit -> Preferences -> Folders -> Plug-ins`, and search for an older binary in each displayed folder of the list (except `/usr/lib/gimp/2.0/plug-ins` which is the installation folder used to store the plugin by the `.deb` file).

> I just realized I'm actually talking to the author of the software! 

Yes, there are not many other people to answer on the github issues :) Thanks for the kind words!

**Comment by totetmatt** [comment]
Similar issue with gmic 3.1.4 Windows + GIMP with Color Preset also (but underneath it's the same script I think)

**Comment by dtschump** [comment]
Should be fixed in latest release 3.2.0. 
3.2.1 release planed for tomorrow.
