### ISSUE TITLE
Extract Foreground error report

### ISSUE THREAD

**Issue by starsareintherose** [GreycLab/gmic#430]
Description:
Extract Foreground error report

Additional info:
- OS: archlinux
- DE: gnome 43.2
- GIMP: 2.10
- GMIC: 3.20
Steps to reproduce:
- `env QT_QPA_PLATFORM=wayland gimp` [to avoid QT_QPA_PLATFORM=wayland warning]
- GMIC-QT -> contours -> Extract Foreground [interactive]
- window error report
```
*** Error in ./fx_ extract foreground/*foreach/*if/ ***
Command 'name': Number of arguments (2) cannot be higherthan the number of images in the selection (1).
```
- terminal report
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

**Comment by dtschump** [comment]
I confim this.
Commit https://github.com/GreycLab/gmic/commit/25f5c63ea311cc2e35ca2d36ef65e3d8567ea0aa should fix this issue.
I've pushed filter updates, so in the plug-in, try pressing the 'Update Button' and it should be OK.

**Comment by starsareintherose** [comment]
Building pkg with patch, the issue is not solved, same error

**Comment by dtschump** [comment]
I can see why. Have you tried the 'Update filters' button ?
I've pushed a filter update, but theoretically, I should also regenerate the corresponding file `gmic_stdlib.h`, from `gmic_stdlib.gmic` , but I don't do that each time I make a modification in this file.

**Comment by starsareintherose** [comment]
It said no download is needed and same error, my OS is arch

**Comment by dtschump** [comment]
> It said no download is needed

It never says that. Are you sure you pushed the `Update filters` button from the plugin GUI ?

![gmic_plugin](https://user-images.githubusercontent.com/10114565/216836906-030a0bb1-ab99-4a4f-9a28-d99ac04ea430.jpg)

**Comment by starsareintherose** [comment]
Sorry, my fault, I forget to select internet
